import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";
import { useRouter } from "next/router";
import { useState } from "react";
import { BuildingOfficeIcon, CheckIcon } from "@heroicons/react/24/outline";
import { HeroBanner } from "~/components/HeroBanner";
import { Testimonial } from "~/components/Testimonial";
import MarketingNavBar from "~/components/MarketingNavBar";
import Footer from "~/components/Footer";
import { Test } from "mocha";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const router = useRouter();
  const [orgName, setOrgName] = useState("");
  const currentUserOrganizationAndRole = api.user?.getUserOrganization.useQuery(
    sessionData?.user.id ? sessionData?.user.id : ""
  );

  if (currentUserOrganizationAndRole.data?.organizationId) {
    if (
      currentUserOrganizationAndRole.data?.role === "OWNER" ||
      currentUserOrganizationAndRole.data?.role === "ADMIN"
    ) {
      void router.push("/admin");
    } else {
      void router.push("/user");
    }
  }
  const createOrganization = api.organization?.createOrganization.useMutation({
    onSuccess: () => {
      void router.push("/admin");
    },
  });
  return (
    <>
      <Head>
        <title>HoneyDew</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {sessionData ? (
        <main className="flex min-h-screen ">
          <div className="flex w-2/5 flex-col items-start gap-8 bg-gradient-to-tr from-indigo-700 to-indigo-300 pl-24 pt-72">
            <h1 className="inline-block bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-indigo-100 via-cyan-200 to-purple-100 bg-clip-text text-7xl font-bold text-transparent">
              Honeydew
            </h1>
            <div className="flex gap-4">
              <div className="h-fit rounded-full border-2 border-blue-100 p-2">
                <CheckIcon className="h-8 w-8 text-blue-100" />
              </div>
              <div className="flex flex-col items-start">
                <h1 className="text-xl font-bold text-white">Logged in</h1>
                <p className="text-white">
                  {sessionData && (
                    <span>Logged in as {sessionData.user?.name} </span>
                  )}
                </p>
              </div>
            </div>
            <div className="flex gap-4">
              <div className="rounded-full border-2 border-gray-100 p-2">
                <BuildingOfficeIcon className="h-8 w-8 text-gray-100" />
              </div>
              <div className="flex flex-col">
                <h1 className="text-xl font-bold text-white">
                  Organization details
                </h1>
                <p className="text-white">Organization details</p>
              </div>
            </div>
          </div>
          <div className="container flex w-3/5 flex-col items-center justify-center gap-12 px-4 py-16 ">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
              <div className="">
                <h3 className="text-2xl font-medium">Organization Name</h3>
                <form
                  onSubmit={() => {
                    createOrganization.mutate({
                      user_id: sessionData.user?.id,
                      organization_name: orgName,
                    });
                  }}
                >
                  <input
                    value={orgName}
                    onChange={(e) => setOrgName(e.target.value)}
                    required
                    placeholder="Alpha Sigma Beta"
                    className="mt-8 w-full rounded-lg border p-4"
                  />
                  <button className="mb-2 mr-2 mt-3 w-full rounded-lg bg-indigo-600 px-5 py-2.5 text-sm font-medium text-white hover:bg-indigo-800 focus:outline-none focus:ring-4 focus:ring-indigo-300">
                    Continue
                  </button>
                </form>
              </div>
            </div>
          </div>
        </main>
      ) : (
        <main className="flex min-h-screen flex-col justify-between">
          <MarketingNavBar />
          <HeroBanner />
          <Testimonial />
          <Footer />
        </main>
      )}
    </>
  );
};

export default Home;
